export function createInitialState() {
    return {
        currentView: 'boot',
        fatalError: null,
        selectedStudentId: null,
        searchQuery: '',
        draftEntry: {
            note: '',
        },
        pendingPhotos: [],
        selectedDateTab: null,
        editState: {
            mode: 'idle',
            isComposerExpanded: false,
            isEditing: false,
            addStudentDialogOpen: false,
            addStudentName: '',
            addStudentError: null,
            renameStudentDialogOpen: false,
            renameStudentId: null,
            renameStudentName: '',
            renameStudentError: null,
            deleteStudentDialogOpen: false,
            deleteStudentId: null,
            deleteStudentName: '',
            deleteStudentError: null,
            photoProcessingErrors: [],
            entryCreateError: null,
            editingEntryId: null,
            editingEntryDate: null,
            retainedEntryPhotos: [],
            deleteEntryDialogOpen: false,
            deleteEntryId: null,
            deleteEntryDate: null,
            deleteEntryError: null,
            activePhotoUrl: null,
        },
        asyncFlags: {
            isBooting: true,
            isDbReady: false,
            isRouteLoading: false,
            isCreatingStudent: false,
            isRenamingStudent: false,
            isDeletingStudent: false,
            isProcessingPhotos: false,
            isSavingEntry: false,
        },
        route: null,
        routeData: {
            students: [],
            selectedStudent: null,
            availableDates: [],
            dateGroups: [],
            selectedEntries: [],
        },
        db: {
            isReady: false,
            isSupported: false,
            error: null,
        },
    };
}
